module.exports = {
	name: 'testView3_5And3_4And3_3And3_2And3_1',
	config: {
		tV01: { _vid: 'tV01', _flexo: {type: 'read', scheme: ['testFlexo3_5', '_id']}},
		tV02: { _vid: 'tV02', _flexo: {type: 'read', scheme: ['testFlexo3_5', 'tsUpdate']}},

		tV03: { _vid: 'tV03', _flexo: {type: 'read', scheme: ['testFlexo3_5', 'field1']}},
		tV04: { _vid: 'tV04', _flexo: {type: 'read', scheme: ['testFlexo3_5', 'field2']}},
		tV05: { _vid: 'tV05', _flexo: {type: 'read', scheme: ['testFlexo3_5', 'field3']}},
		tV06: { _vid: 'tV06', _flexo: {type: 'read', scheme: ['testFlexo3_5', 'field4']}},
		tV07: { _vid: 'tV07', _flexo: {type: 'read', scheme: ['testFlexo3_5', 'field5']}},
		tV08: { _vid: 'tV08', _flexo: {type: 'read', scheme: ['testFlexo3_5', 'field6']}},
		tV09: { _vid: 'tV09', _flexo: {type: 'read', scheme: ['testFlexo3_5', 'field7']}},
		tV10: { _vid: 'tV10', _flexo: {type: 'read', scheme: ['testFlexo3_5', 'field8']}},
		tV11: { _vid: 'tV11', _flexo: {type: 'read', scheme: ['testFlexo3_5', 'field9']}},
		tV12: { _vid: 'tV12', _flexo: {type: 'read', scheme: ['testFlexo3_5', 'field10']}},
		tV13: { _vid: 'tV13', _flexo: {type: 'read', scheme: ['testFlexo3_5', 'field11']}},
		tV14: { _vid: 'tV14', _flexo: {type: 'read', scheme: ['testFlexo3_5', 'field12']}},
		tV15: { _vid: 'tV15', _flexo: {type: 'read', scheme: ['testFlexo3_5', 'field13']}},
		tV16: { _vid: 'tV16', _flexo: {type: 'read', scheme: ['testFlexo3_5', 'field14']}},
		tV17: { _vid: 'tV17', _flexo: {type: 'read', scheme: ['testFlexo3_5', 'field15']}},
		tV18: { _vid: 'tV18', _flexo: {type: 'read', scheme: ['testFlexo3_5', 'field16']}},

		tV19: { _vid: 'tV19', _flexo: {type: 'read', scheme: ['testFlexo3_4', '_id', 'field16']}},
		tV20: { _vid: 'tV20', _flexo: {type: 'read', scheme: ['testFlexo3_4', 'tsUpdate', 'field16']}},

		tV21: { _vid: 'tV21', _flexo: {type: 'read', scheme: ['testFlexo3_4', 'field1', 'field16']}},
		tV22: { _vid: 'tV22', _flexo: {type: 'read', scheme: ['testFlexo3_4', 'field2', 'field16']}},
		tV23: { _vid: 'tV23', _flexo: {type: 'read', scheme: ['testFlexo3_4', 'field3', 'field16']}},
		tV24: { _vid: 'tV24', _flexo: {type: 'read', scheme: ['testFlexo3_4', 'field4', 'field16']}},
		tV25: { _vid: 'tV25', _flexo: {type: 'read', scheme: ['testFlexo3_4', 'field5', 'field16']}},
		tV26: { _vid: 'tV26', _flexo: {type: 'read', scheme: ['testFlexo3_4', 'field6', 'field16']}},
		tV27: { _vid: 'tV27', _flexo: {type: 'read', scheme: ['testFlexo3_4', 'field7', 'field16']}},
		tV28: { _vid: 'tV28', _flexo: {type: 'read', scheme: ['testFlexo3_4', 'field8', 'field16']}},
		tV29: { _vid: 'tV29', _flexo: {type: 'read', scheme: ['testFlexo3_4', 'field9', 'field16']}},
		tV30: { _vid: 'tV30', _flexo: {type: 'read', scheme: ['testFlexo3_4', 'field10', 'field16']}},
		tV31: { _vid: 'tV31', _flexo: {type: 'read', scheme: ['testFlexo3_4', 'field11', 'field16']}},
		tV32: { _vid: 'tV32', _flexo: {type: 'read', scheme: ['testFlexo3_4', 'field12', 'field16']}},
		tV33: { _vid: 'tV33', _flexo: {type: 'read', scheme: ['testFlexo3_4', 'field13', 'field16']}},
		tV34: { _vid: 'tV34', _flexo: {type: 'read', scheme: ['testFlexo3_4', 'field14', 'field16']}},
		tV35: { _vid: 'tV35', _flexo: {type: 'read', scheme: ['testFlexo3_4', 'field15', 'field16']}},
		tV36: { _vid: 'tV36', _flexo: {type: 'read', scheme: ['testFlexo3_4', 'field16', 'field16']}},

		tV37: { _vid: 'tV37', _flexo: {type: 'read', scheme: ['testFlexo3_3', '_id', 'field16', 'linkFlexo3']}},
		tV38: { _vid: 'tV38', _flexo: {type: 'read', scheme: ['testFlexo3_3', 'tsUpdate', 'field16', 'linkFlexo3']}},

		tV39: { _vid: 'tV39', _flexo: {type: 'read', scheme: ['testFlexo3_3', 'field1', 'field16', 'linkFlexo3']}},
		tV40: { _vid: 'tV40', _flexo: {type: 'read', scheme: ['testFlexo3_3', 'field2', 'field16', 'linkFlexo3']}},
		tV41: { _vid: 'tV41', _flexo: {type: 'read', scheme: ['testFlexo3_3', 'field3', 'field16', 'linkFlexo3']}},
		tV42: { _vid: 'tV42', _flexo: {type: 'read', scheme: ['testFlexo3_3', 'field4', 'field16', 'linkFlexo3']}},
		tV43: { _vid: 'tV43', _flexo: {type: 'read', scheme: ['testFlexo3_3', 'field5', 'field16', 'linkFlexo3']}},
		tV44: { _vid: 'tV44', _flexo: {type: 'read', scheme: ['testFlexo3_3', 'field6', 'field16', 'linkFlexo3']}},
		tV45: { _vid: 'tV45', _flexo: {type: 'read', scheme: ['testFlexo3_3', 'field7', 'field16', 'linkFlexo3']}},
		tV46: { _vid: 'tV46', _flexo: {type: 'read', scheme: ['testFlexo3_3', 'field8', 'field16', 'linkFlexo3']}},
		tV47: { _vid: 'tV47', _flexo: {type: 'read', scheme: ['testFlexo3_3', 'field9', 'field16', 'linkFlexo3']}},
		tV48: { _vid: 'tV48', _flexo: {type: 'read', scheme: ['testFlexo3_3', 'field10', 'field16', 'linkFlexo3']}},
		tV49: { _vid: 'tV49', _flexo: {type: 'read', scheme: ['testFlexo3_3', 'field11', 'field16', 'linkFlexo3']}},
		tV50: { _vid: 'tV50', _flexo: {type: 'read', scheme: ['testFlexo3_3', 'field12', 'field16', 'linkFlexo3']}},
		tV51: { _vid: 'tV51', _flexo: {type: 'read', scheme: ['testFlexo3_3', 'field13', 'field16', 'linkFlexo3']}},
		tV52: { _vid: 'tV52', _flexo: {type: 'read', scheme: ['testFlexo3_3', 'field14', 'field16', 'linkFlexo3']}},
		tV53: { _vid: 'tV53', _flexo: {type: 'read', scheme: ['testFlexo3_3', 'field15', 'field16', 'linkFlexo3']}},
		tV54: { _vid: 'tV54', _flexo: {type: 'read', scheme: ['testFlexo3_3', 'field16', 'field16', 'linkFlexo3']}},

		tV55: { _vid: 'tV55', _flexo: {type: 'read', scheme: ['testFlexo3_2', '_id', 'field16', 'linkFlexo3']}},
		tV56: { _vid: 'tV56', _flexo: {type: 'read', scheme: ['testFlexo3_2', 'tsUpdate', 'field16', 'linkFlexo3']}},

		tV57: { _vid: 'tV57', _flexo: {type: 'read', scheme: ['testFlexo3_2', 'field1', 'field16', 'linkFlexo3']}},
		tV58: { _vid: 'tV58', _flexo: {type: 'read', scheme: ['testFlexo3_2', 'field2', 'field16', 'linkFlexo3']}},
		tV59: { _vid: 'tV59', _flexo: {type: 'read', scheme: ['testFlexo3_2', 'field3', 'field16', 'linkFlexo3']}},
		tV60: { _vid: 'tV60', _flexo: {type: 'read', scheme: ['testFlexo3_2', 'field4', 'field16', 'linkFlexo3']}},
		tV61: { _vid: 'tV61', _flexo: {type: 'read', scheme: ['testFlexo3_2', 'field5', 'field16', 'linkFlexo3']}},
		tV62: { _vid: 'tV62', _flexo: {type: 'read', scheme: ['testFlexo3_2', 'field6', 'field16', 'linkFlexo3']}},
		tV63: { _vid: 'tV63', _flexo: {type: 'read', scheme: ['testFlexo3_2', 'field7', 'field16', 'linkFlexo3']}},
		tV64: { _vid: 'tV64', _flexo: {type: 'read', scheme: ['testFlexo3_2', 'field8', 'field16', 'linkFlexo3']}},
		tV65: { _vid: 'tV65', _flexo: {type: 'read', scheme: ['testFlexo3_2', 'field9', 'field16', 'linkFlexo3']}},
		tV66: { _vid: 'tV66', _flexo: {type: 'read', scheme: ['testFlexo3_2', 'field10', 'field16', 'linkFlexo3']}},
		tV67: { _vid: 'tV67', _flexo: {type: 'read', scheme: ['testFlexo3_2', 'field11', 'field16', 'linkFlexo3']}},
		tV68: { _vid: 'tV68', _flexo: {type: 'read', scheme: ['testFlexo3_2', 'field12', 'field16', 'linkFlexo3']}},
		tV69: { _vid: 'tV69', _flexo: {type: 'read', scheme: ['testFlexo3_2', 'field13', 'field16', 'linkFlexo3']}},
		tV70: { _vid: 'tV70', _flexo: {type: 'read', scheme: ['testFlexo3_2', 'field14', 'field16', 'linkFlexo3']}},
		tV71: { _vid: 'tV71', _flexo: {type: 'read', scheme: ['testFlexo3_2', 'field15', 'field16', 'linkFlexo3']}},
		tV72: { _vid: 'tV72', _flexo: {type: 'read', scheme: ['testFlexo3_2', 'field16', 'field16', 'linkFlexo3']}},

		tV73: { _vid: 'tV73', _flexo: {type: 'read', scheme: ['testFlexo3_1', '_id', 'field16', 'linkFlexo3']}},
		tV74: { _vid: 'tV74', _flexo: {type: 'read', scheme: ['testFlexo3_1', 'tsUpdate', 'field16', 'linkFlexo3']}},

		tV75: { _vid: 'tV75', _flexo: {type: 'read', scheme: ['testFlexo3_1', 'field1', 'field16', 'linkFlexo3']}},
		tV76: { _vid: 'tV76', _flexo: {type: 'read', scheme: ['testFlexo3_1', 'field2', 'field16', 'linkFlexo3']}},
		tV77: { _vid: 'tV77', _flexo: {type: 'read', scheme: ['testFlexo3_1', 'field3', 'field16', 'linkFlexo3']}},
		tV78: { _vid: 'tV78', _flexo: {type: 'read', scheme: ['testFlexo3_1', 'field4', 'field16', 'linkFlexo3']}},
		tV79: { _vid: 'tV79', _flexo: {type: 'read', scheme: ['testFlexo3_1', 'field5', 'field16', 'linkFlexo3']}},
		tV80: { _vid: 'tV80', _flexo: {type: 'read', scheme: ['testFlexo3_1', 'field6', 'field16', 'linkFlexo3']}},
		tV81: { _vid: 'tV81', _flexo: {type: 'read', scheme: ['testFlexo3_1', 'field7', 'field16', 'linkFlexo3']}},
		tV82: { _vid: 'tV82', _flexo: {type: 'read', scheme: ['testFlexo3_1', 'field8', 'field16', 'linkFlexo3']}},
		tV83: { _vid: 'tV83', _flexo: {type: 'read', scheme: ['testFlexo3_1', 'field9', 'field16', 'linkFlexo3']}},
		tV84: { _vid: 'tV84', _flexo: {type: 'read', scheme: ['testFlexo3_1', 'field10', 'field16', 'linkFlexo3']}},
		tV85: { _vid: 'tV85', _flexo: {type: 'read', scheme: ['testFlexo3_1', 'field11', 'field16', 'linkFlexo3']}},
		tV86: { _vid: 'tV86', _flexo: {type: 'read', scheme: ['testFlexo3_1', 'field12', 'field16', 'linkFlexo3']}},
		tV87: { _vid: 'tV87', _flexo: {type: 'read', scheme: ['testFlexo3_1', 'field13', 'field16', 'linkFlexo3']}},
		tV88: { _vid: 'tV88', _flexo: {type: 'read', scheme: ['testFlexo3_1', 'field14', 'field16', 'linkFlexo3']}},
		tV89: { _vid: 'tV89', _flexo: {type: 'read', scheme: ['testFlexo3_1', 'field15', 'field16', 'linkFlexo3']}}

	},
	root:'testFlexo3_5'
};