module.exports = {
	name: 'testView1_3And1_2And1_1',
	config: {
		tV01: { _vid: 'tV01', _flexo: {type: 'read', scheme: ['testFlexo1_3', '_id']}},
		tV02: { _vid: 'tV02', _flexo: {type: 'read', scheme: ['testFlexo1_3', 'tsUpdate']}},

		tV03: { _vid: 'tV03', _flexo: {type: 'read', scheme: ['testFlexo1_3', 'field1']}},
		tV04: { _vid: 'tV04', _flexo: {type: 'read', scheme: ['testFlexo1_3', 'field2']}},
		tV05: { _vid: 'tV05', _flexo: {type: 'read', scheme: ['testFlexo1_3', 'field3']}},
		tV06: { _vid: 'tV06', _flexo: {type: 'read', scheme: ['testFlexo1_3', 'field4']}},
		tV07: { _vid: 'tV07', _flexo: {type: 'read', scheme: ['testFlexo1_3', 'field5']}},
		tV08: { _vid: 'tV08', _flexo: {type: 'read', scheme: ['testFlexo1_3', 'field6']}},
		tV09: { _vid: 'tV09', _flexo: {type: 'read', scheme: ['testFlexo1_3', 'field7']}},
		tV10: { _vid: 'tV10', _flexo: {type: 'read', scheme: ['testFlexo1_3', 'field8']}},
		tV11: { _vid: 'tV11', _flexo: {type: 'read', scheme: ['testFlexo1_3', 'field9']}},
		tV12: { _vid: 'tV12', _flexo: {type: 'read', scheme: ['testFlexo1_3', 'field10']}},
		tV13: { _vid: 'tV13', _flexo: {type: 'read', scheme: ['testFlexo1_3', 'field11']}},
		tV14: { _vid: 'tV14', _flexo: {type: 'read', scheme: ['testFlexo1_3', 'field12']}},
		tV15: { _vid: 'tV15', _flexo: {type: 'read', scheme: ['testFlexo1_3', 'field13']}},
		tV16: { _vid: 'tV16', _flexo: {type: 'read', scheme: ['testFlexo1_3', 'field14']}},
		tV17: { _vid: 'tV17', _flexo: {type: 'read', scheme: ['testFlexo1_3', 'field15']}},
		tV18: { _vid: 'tV18', _flexo: {type: 'read', scheme: ['testFlexo1_3', 'field16']}},

		tV19: { _vid: 'tV19', _flexo: {type: 'read', scheme: ['testFlexo1_2', '_id', 'field16']}},
		tV20: { _vid: 'tV20', _flexo: {type: 'read', scheme: ['testFlexo1_2', 'tsUpdate', 'field16']}},

		tV21: { _vid: 'tV21', _flexo: {type: 'read', scheme: ['testFlexo1_2', 'field1', 'field16']}},
		tV22: { _vid: 'tV22', _flexo: {type: 'read', scheme: ['testFlexo1_2', 'field2', 'field16']}},
		tV23: { _vid: 'tV23', _flexo: {type: 'read', scheme: ['testFlexo1_2', 'field3', 'field16']}},
		tV24: { _vid: 'tV24', _flexo: {type: 'read', scheme: ['testFlexo1_2', 'field4', 'field16']}},
		tV25: { _vid: 'tV25', _flexo: {type: 'read', scheme: ['testFlexo1_2', 'field5', 'field16']}},
		tV26: { _vid: 'tV26', _flexo: {type: 'read', scheme: ['testFlexo1_2', 'field6', 'field16']}},
		tV27: { _vid: 'tV27', _flexo: {type: 'read', scheme: ['testFlexo1_2', 'field7', 'field16']}},
		tV28: { _vid: 'tV28', _flexo: {type: 'read', scheme: ['testFlexo1_2', 'field8', 'field16']}},
		tV29: { _vid: 'tV29', _flexo: {type: 'read', scheme: ['testFlexo1_2', 'field9', 'field16']}},
		tV30: { _vid: 'tV30', _flexo: {type: 'read', scheme: ['testFlexo1_2', 'field10', 'field16']}},
		tV31: { _vid: 'tV31', _flexo: {type: 'read', scheme: ['testFlexo1_2', 'field11', 'field16']}},
		tV32: { _vid: 'tV32', _flexo: {type: 'read', scheme: ['testFlexo1_2', 'field12', 'field16']}},
		tV33: { _vid: 'tV33', _flexo: {type: 'read', scheme: ['testFlexo1_2', 'field13', 'field16']}},
		tV34: { _vid: 'tV34', _flexo: {type: 'read', scheme: ['testFlexo1_2', 'field14', 'field16']}},
		tV35: { _vid: 'tV35', _flexo: {type: 'read', scheme: ['testFlexo1_2', 'field15', 'field16']}},
		tV36: { _vid: 'tV36', _flexo: {type: 'read', scheme: ['testFlexo1_2', 'field16', 'field16']}},

		tV37: { _vid: 'tV19', _flexo: {type: 'read', scheme: ['testFlexo1_1', '_id', 'field16', 'linkFlexo1']}},
		tV38: { _vid: 'tV20', _flexo: {type: 'read', scheme: ['testFlexo1_1', 'tsUpdate', 'field16', 'linkFlexo1']}},

		tV39: { _vid: 'tV21', _flexo: {type: 'read', scheme: ['testFlexo1_1', 'field1', 'field16', 'linkFlexo1']}},
		tV40: { _vid: 'tV22', _flexo: {type: 'read', scheme: ['testFlexo1_1', 'field2', 'field16', 'linkFlexo1']}},
		tV41: { _vid: 'tV23', _flexo: {type: 'read', scheme: ['testFlexo1_1', 'field3', 'field16', 'linkFlexo1']}},
		tV42: { _vid: 'tV24', _flexo: {type: 'read', scheme: ['testFlexo1_1', 'field4', 'field16', 'linkFlexo1']}},
		tV43: { _vid: 'tV25', _flexo: {type: 'read', scheme: ['testFlexo1_1', 'field5', 'field16', 'linkFlexo1']}},
		tV44: { _vid: 'tV26', _flexo: {type: 'read', scheme: ['testFlexo1_1', 'field6', 'field16', 'linkFlexo1']}},
		tV45: { _vid: 'tV27', _flexo: {type: 'read', scheme: ['testFlexo1_1', 'field7', 'field16', 'linkFlexo1']}},
		tV46: { _vid: 'tV28', _flexo: {type: 'read', scheme: ['testFlexo1_1', 'field8', 'field16', 'linkFlexo1']}},
		tV47: { _vid: 'tV29', _flexo: {type: 'read', scheme: ['testFlexo1_1', 'field9', 'field16', 'linkFlexo1']}},
		tV48: { _vid: 'tV30', _flexo: {type: 'read', scheme: ['testFlexo1_1', 'field10', 'field16', 'linkFlexo1']}},
		tV49: { _vid: 'tV31', _flexo: {type: 'read', scheme: ['testFlexo1_1', 'field11', 'field16', 'linkFlexo1']}},
		tV50: { _vid: 'tV32', _flexo: {type: 'read', scheme: ['testFlexo1_1', 'field12', 'field16', 'linkFlexo1']}},
		tV51: { _vid: 'tV33', _flexo: {type: 'read', scheme: ['testFlexo1_1', 'field13', 'field16', 'linkFlexo1']}},
		tV52: { _vid: 'tV34', _flexo: {type: 'read', scheme: ['testFlexo1_1', 'field14', 'field16', 'linkFlexo1']}},
		tV53: { _vid: 'tV35', _flexo: {type: 'read', scheme: ['testFlexo1_1', 'field15', 'field16', 'linkFlexo1']}}
	},
	root:'testFlexo1_3'
};
